version: '3.5'
services:
    backend:
        build:
            dockerfile: Dockerfile
            context: ./backend
        volumes:
            #- /app/node_modules
            - ./backend:/app
        ports: 
            - '8081:8080'
    # nginx:
    #     restart: always
    #     build:
    #       dockerfile: Dockerfile
    #       context: ./controller
    #     ports:
    #       - '5000:80'
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./
        volumes:
            - /app/node_modules
            #- ./frontend:/app
        ports: 
            - '4200:80'
